export const CHANGE_FIELD_VISIBILITY = Symbol('CHANGE_FIELD_VISIBILITY')
export const TOGGLE_ROW_CHECK = Symbol('TOGGLE_ROW_CHECK')
export const TOGGLE_HEADER_CHECK_ALL = Symbol('TOGGLE_HEADER_CHECK_ALL')
export const TOGGLE_ROW_CHECKBOX_CHECK = Symbol('TOGGLE_ROW_CHECKBOX_CHECK')

// fetching data
export const GET_STATUS = Symbol('GET_STATUS')
export const FETCH_REPORTS = Symbol('FETCH_REPORTS')
export const NOTIFICATIONS_UPDATE_PAGINATION = Symbol('NOTIFICATIONS_UPDATE_PAGINATION')
