export const TOGGLE_DIALOG_VISIBILITY = Symbol('TOGGLE_DIALOG_VISIBILITY')
export const CHANGE_FIELD_VALUE = Symbol('CHANGE_FIELD_VALUE')
export const CREATE_TEMPLATE = Symbol('CREATE_TEMPLATE')
export const CLEAR_DETAIL = Symbol('CLEAR_DETAIL')
export const MERGE_EDIT_FIELDS = Symbol('MERGE_EDIT_FIELDS')
export const EDIT_TEMPLATE = Symbol('EDIT_TEMPLATE')
export const RESET_FIELDS = Symbol('RESET_FIELDS')
export const SET_PURPOSE = Symbol('SET_PURPOSE')
